### 행렬의 정렬

1. np.sort() : 넘파이에서 sort() 호출

2. nparray.sort() : 행렬자체에서 sort() 호출


####  두 방식 sort() 함수의 차이점


1. np.sort() : 원 행렬을 그대로 유지한채 원 행렬의 정렬된 행렬을 반환

2. nparray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 None을 반환

In [1]:
import numpy as np

origin = np.array([3,1,9,7])
print('원본:', origin)

원본: [3 1 9 7]


In [2]:
# 넘파이 sort
sort1 = np.sort(origin)
print('넘파이:', sort1)

넘파이: [1 3 7 9]


In [6]:
# 행렬의 sort
sort2 = origin.sort()
print('nparray:', sort2)

nparray: None


### 내림차순 정렬 [::-1]

In [7]:
origin = np.array([3,1,9,7])
print('원본:', origin)

원본: [3 1 9 7]


In [9]:
sort1 = np.sort(origin)[::-1]
print('넘파이:', sort1)

넘파이: [9 7 3 1]


In [11]:
sort2 = origin.sort()[::-1]
print('nparray:', sort2) # TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

### 2차원 이상의 행렬에서

- axis=0 : 행방향 -> 열단위
- axis=1 : 열방향 -> 행단위

In [15]:
arr = np.array([[9, 6, 3],[5, 11, 2]])

arr2 = np.sort(arr, axis=0)
print(arr2)

arr3 = np.sort(arr, axis=1)
print(arr3)

[[ 5  6  2]
 [ 9 11  3]]
[[ 3  6  9]
 [ 2  5 11]]


In [5]:
?np.sort

####  정렬된 행렬의 인덱스 반환 : argsort()

In [16]:
arr = np.array([3, 8, 2, 5])

idx = np.argsort(arr)
idx  # array([2, 0, 3, 1])



array([2, 0, 3, 1])

In [27]:
scores = np.array([66, 99, 88, 44, 77])
names = np.array(['홍길','박길','최길','맹길','김길'])

# 성적순으로 점수와 이름을 매핑
idx = np.argsort(scores)

AttributeError: 'builtin_function_or_method' object has no attribute 'scores'